#! /usr/bin/env python3
# Copyright (c) 2021-2022 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

from os.path import dirname, join
import sys

src_path = join(dirname(__file__), "src")
sys.path.insert(0, src_path)

from git_acquire.__main__ import main  # noqa: E402

main()
